import { ITRequest, RequestStatus } from './types';

export const MOCK_REQUESTS: ITRequest[] = [
  {
    id: 'TICKET-001',
    requesterId: 'user-1',
    firstName: 'Alice',
    lastName: 'Johnson',
    department: 'Marketing',
    email: 'alice.j@example.com',
    contactNumber: '555-0101',
    problemCategories: ['Computer', 'Network'],
    otherCategoryDetail: '',
    details: 'My computer is running very slow and I am unable to connect to the shared network drive.',
    comments: 'This has been happening since yesterday morning.',
    status: RequestStatus.New,
    submittedAt: new Date('2023-10-26T09:00:00Z'),
  },
  {
    id: 'TICKET-002',
    requesterId: 'user-2',
    firstName: 'Bob',
    lastName: 'Smith',
    department: 'Sales',
    email: 'bob.s@example.com',
    contactNumber: '555-0102',
    problemCategories: ['Email'],
    otherCategoryDetail: '',
    details: 'I am not receiving any new emails in my Outlook client.',
    comments: 'I have already tried restarting my computer.',
    status: RequestStatus.InProgress,
    submittedAt: new Date('2023-10-26T10:30:00Z'),
  },
  {
    id: 'TICKET-003',
    requesterId: 'user-3',
    firstName: 'Charlie',
    lastName: 'Brown',
    department: 'Engineering',
    email: 'charlie.b@example.com',
    contactNumber: '555-0103',
    problemCategories: ['Other'],
    otherCategoryDetail: 'Projector in conference room 3 is not working.',
    details: 'The projector bulb seems to be burnt out. We have a major presentation in two hours.',
    comments: '',
    status: RequestStatus.Resolved,
    submittedAt: new Date('2023-10-25T14:00:00Z'),
    resolvedBy: 'Jane Smith',
    remarks: 'Projector bulb replaced. Tested and working.',
  },
  {
    id: 'TICKET-004',
    requesterId: 'user-1',
    firstName: 'Alice',
    lastName: 'Johnson',
    department: 'Marketing',
    email: 'alice.j@example.com',
    contactNumber: '555-0101',
    problemCategories: ['Phone'],
    otherCategoryDetail: '',
    details: 'My desk phone has no dial tone.',
    comments: 'Model is Cisco 7841.',
    status: RequestStatus.Closed,
    submittedAt: new Date('2023-10-24T11:00:00Z'),
    resolvedBy: 'John Doe',
    closedAt: new Date('2023-10-25T16:30:00Z'),
    remarks: 'Line was faulty. Replaced desk phone.',
  },
   {
    id: 'TICKET-005',
    requesterId: 'user-4',
    firstName: 'Eve',
    lastName: 'Adams',
    department: 'Finance',
    email: 'eve.a@example.com',
    contactNumber: '555-0105',
    problemCategories: ['Computer'],
    otherCategoryDetail: '',
    details: 'Requesting installation of new accounting software (QuickBooks 2023).',
    comments: 'License key is attached to the internal request.',
    status: RequestStatus.New,
    submittedAt: new Date('2023-10-27T08:15:00Z'),
  },
];